### ISSUE TITLE
beta version not working

### ISSUE THREAD

**Issue by bjgood** [OldManJax/plugin.video.watchnixtoons2#2]
Hi,
The beta was working yesterday, but today it is not.
Thank you.

**Comment by OldManJax** [comment]
Is it an issue with some or all videos? I just tested it on my PC and it played fine for me. I do have an issue with some titles, however the developer can't see any problems so we aren't sure why. It should be working the same way for everyone, unless it's an ISP issue.

**Comment by bjgood** [comment]
Hi,
From the videos I've tried, none have worked. What videos did you try?
Thank you.

**Comment by bjgood** [comment]
Here is a snippet of the Kodi LibreELEC error log...

2024-11-24 09:38:27.949 T:4713    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'group'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.watchnixtoons2/default.py", line 5, in <module>
                                                       main()
                                                     File "/storage/.kodi/addons/plugin.video.watchnixtoons2/lib/plugin.py", line 1749, in main
                                                       globals()[params.get('action', 'actionMenu')](params)
                                                     File "/storage/.kodi/addons/plugin.video.watchnixtoons2/lib/plugin.py", line 1568, in actionResolve
                                                       sources_block = re.search(r'sources:\s*?\[(.*?)\]', html, re.DOTALL).group(1)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'group'
                                                   -->End of Python script error report<--
                                                   
2024-11-24 09:38:28.067 T:844     error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.watchnixtoons2/?action=actionResolve&url=%2Fhey-arnold-season-1-episode-1-downtown-as-fruits-eugene-s-bike]

I'm also running a VPN.
Hope it helps.
Thank you.

**Comment by OldManJax** [comment]
I played the first video under A from each category without issue so we know the add-on is working for some. I use it without a VPN on a PC and an Nvidia Shield 2019. Both on Kodi 21.1.
So this could be an issue with either your VPN or how the RPi4 works. It's the only thing I can't test. I will pass this information onto the developer. I understand the coding about as much as you do. lol

**Comment by bjgood** [comment]
If it's working you and others, it appears I'm being blocked by some means. Probably my ISP.
Thanks for the reply.

**Comment by OldManJax** [comment]
Ah! good to know. I will give the dev a heads up for future reference. Appreciate the input.

**Comment by TommyTaif** [comment]
Hi,

I am having the same problem with the beta and the current release (0.12.7). I am running on a RaspberryPi 4 with the latest RaspiOS (bookworm) and Kodi 20.5 from the standard RasPi repo.  
I was looking at the data in the html variable and found that watchanimesub.net has blocked the request from Kodi / watchnixtoons

Here the response:
```
Please enable cookies.
Sorry, you have been blocked
You are unable to access watchanimesub.net
Why have I been blocked?

This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.
What can I do to resolve this?

You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.

Cloudflare Ray ID: 8e3a27ec4ed58f40 • Your IP: • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)
```

The all works fine on an old Kodi Leia (running on a RetroPie installation) and from an Android device on the same network.

I would appreciate if you found the time to look into that, but could also understand if that is too much of a niche problem. It is working great on any other platform I tested.

Cheers

**Comment by OldManJax** [comment]
Now I'm really confused. This add-on doesn't use watchanimesub.net, it pulls from either wcofun.net or wcostream.tv depending on what the settings are set to. I'm not the developer so the actual coding is way over my head.

**Comment by TommyTaif** [comment]
I didn't even notice. It was set to wcofun, but I tried wcostream as well. Are the videos possibly hosted on watchanimesub?

**Comment by OldManJax** [comment]
They can't be as I've been using WNT2 without a problem (for the ones I do watch). If I go to watchanimesub.net in my browser it's a dead server or cloudflare is blocking it. The add-on would never work at all if the files are hosted there.

**Comment by TommyTaif** [comment]
Hi again,

A quick update. I tried the latest release on the same system which gave problems before and it is working perfectly fine now. 

Cheers,
TommyT
